spring.application.name=tpi2SQLite
port=8080

spring.datasource.url=jdbc:sqlite:./tpSQLite.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
